version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: crio-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: criodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./backend
    container_name: crio-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/criodb?schema=public
      - PORT=3001
    ports:
      - "3001:3001"
    restart: unless-stopped
    # Sem volumes pra NÃO sobrescrever o /app/dist dentro do container

  frontend:
    build: ./frontend
    container_name: crio-frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres_data:
